name: Publish to Prod
on: 
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --exclude=".DS_Store"
        path: docs/
        remote_path: ${{ secrets.PATH_PROD }}
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.KEY }}